export const FETCH_POSTS = 'FETCH_POSTS';
export const NEW_POST = 'NEW_POST';
export const ACTION_EXAMPLE_1 = 'ACTION_EXAMPLE_1';
export const ACTION_EXAMPLE_2 = 'ACTION_EXAMPLE_2';
export const ACTION_EXAMPLE_3 = 'ACTION_EXAMPLE_3';


export const ACTION_SHOW_LOADER = 'ACTION_SHOW_LOADER';
export const ACTION_HIDE_LOADER = 'ACTION_HIDE_LOADER';
export const LIST_ACTION_FILTER_PLAYERS = 'LIST_ACTION_FILTER_PLAYERS';
export const ACTION_SET_ERROR_GETTING_DATA = 'ACTION_SET_ERROR_GETTING_DATA';